### PR TITLE
bin support

### PR DESCRIPTION
**Pull request by vdegenne**
Could you review this PR and consider it to be interesting.
I just added a bin file and the **bin** property in the **package.json** file.
So when the package is installed globally `npm i -g get-port` one can actually type the following in the system terminal :

```get-port``` for any available port
```get-port 3000 3020``` for the preferred ports
```get-port -r 3000,3100``` for the range

I found it useful for myself to check if a port is available before using it in my application or sometimes even I just want the system to choose a port that I'll be using fixed throughout my project.

If you think that is interesting, please accept the PR and I let you change the readme to introduce this feature.

### CODE REVIEW

**Comment by vdegenne** [comment]
I fixed the bin file to agree with the es-lint rules, there is a last failing rule however, that I can't fix.
It seems to be a bug : https://github.com/mysticatea/eslint-plugin-node/issues/126
But I tested locally and the bin support is working fine.

**Comment by sindresorhus** [comment]
There's already a CLI, just in a separate package: https://github.com/sindresorhus/get-port-cli PR welcome there if there's anything missing.

**Comment by vdegenne** [comment]
Oh I didn't know.
What is the motivation behind separating both the API and the CLI by the way ?
Given that both the API and the CLI are very small in size, it would have been great to bundle the both together, just my opinion.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ama/issues/17

**Pull request closed without merging**
