### PR TITLE
Adding TypeScript definition

### PR DESCRIPTION
**Pull request by cyounkins**

### CODE REVIEW

**Comment by kevva** [comment]
Even better, add it to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by cyounkins** [comment]
@kevva So @typings is the successor to DefinitelyTyped. They have stated, "The preferred [method] is that we can help get type definition inside packages. This means consumers don't even need to install Typings, and things start working immediately after they install a package."

@typings could someone clarify if ``typings.json`` is necessary in this situation?

**Comment by cyounkins** [comment]
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

The above says the definition file should "be written as external modules". I don't think my definition satisfies that. Can someone @typings confirm? Do I need to use ``declare module``?

**Comment by kevva** [comment]
In the long run, making package authors having to adapt their modules to TypeScript is never going to work out. especially if they aren't using TypeScript themselves. For small modules like this, where API changes happen rarely, it's fine, but for larger projects it's only a burden to keep the typings updated.

**Comment by sindresorhus** [comment]
I'm not interested in having to maintain something I don't personally use, sorry. It would be a lot easier for you to just submit to @typings, instead of having to try to convince every single tiny module to adapt ;)

**Comment by SamVerschueren** [comment]
Just submit the typings file to DefinitelyTyped and use the `--ambient` flag with the `typings` command to install.

**Pull request closed without merging**
